FROM php:8.4-fpm

ARG NODE_VERSION=24

ENV PHP_OPCACHE_ENABLE=0 \
    PHP_OPCACHE_ENABLE_CLI=0 \
    PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 \
    PHP_OPCACHE_INTERNED_STRINGS_BUFFER=8 \
    PHP_OPCACHE_MAX_ACCELERATED_FILES=4000 \
    PHP_OPCACHE_REVALIDATE_FREQ=60 \
    PHP_OPCACHE_FAST_SHUTDOWN=1 \
    PHP_OPCACHE_MEMORY_CONSUMPTION=256

ENV OTEL_PHP_AUTOLOAD_ENABLED=1 \
    OTEL_TRACES_EXPORTER=otlp \
    OTEL_METRICS_EXPORTER=none \
    OTEL_LOGS_EXPORTER=none \
    OTEL_PROPAGATORS=baggage,tracecontext

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libicu-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    apt-utils \
    libonig-dev \
    libmagickwand-dev --no-install-recommends \
    ghostscript --no-install-recommends 

RUN pecl install \
    xdebug \
    opentelemetry \
    imagick

RUN docker-php-ext-enable \
    xdebug \
    opentelemetry \
    imagick

RUN docker-php-ext-configure  gd --with-freetype --with-jpeg

RUN docker-php-ext-install -j$(nproc) \
    gd \
    intl \
    zip \
    bcmath \
    pdo_mysql \
    mbstring \
    pcntl \
    posix \
    exif \
    gettext \
    fileinfo \
    opcache

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN curl -sLS https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y nodejs

RUN usermod -u 1000 www-data

EXPOSE 9000

CMD ["php-fpm"]
